config/routes.rb
Rails.application.routes.draw do

  get "/" => "home#index"

  resources :users
  resources :menu_categories
  resources :menu_items

  get "/owners" => "owners#index"
  get "/customers" => "customers#index"

  get "/signin" => "sessions#new", as: :owner_sessions_page
  post "/signin" => "sessions#create_customer", as: :customer_sessions
  post "/signin-owner" => "sessions#create_owner", as: :owner_sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
    has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
    belongs_to :menu_category
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  '''PASSWORD_FORMAT = /\A
  (?=.{8,})          # Must contain 8 or more characters
  (?=.*\d)           # Must contain a digit
  (?=.*[a-z])        # Must contain a lower case character
  (?=.*[A-Z])        # Must contain an upper case character
  (?=.*[[:^alnum:]]) # Must contain a symbol
  /x'''

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  '''validates :password, 
    presence: true,  
    format: { with: PASSWORD_FORMAT }, 
    confirmation: true, 
    on: :create
  end'''

  validates :password, presence: true
  validate :password_length
  validate :password_lower_case
  validate :password_upper_case
  validate :password_special_char
  validate :password_contains_number

  def password_length
    return if password.length > 7
    errors.add :password, 'must contain at least 8 characters'
  end

  def password_lower_case
    return if !!password.match(/\p{Lower}/)
    errors.add :password, 'must contain at least 1 lowercase'
  end

  def password_upper_case
    return if !!password.match(/\p{Upper}/)
    errors.add :password, 'must contain at least 1 uppercase'
  end

  def password_special_char
    special = "?<>',?[]{}=-)(*&^%$#@`~!"
    regex = /[#{special.gsub(/./){|char| "\\#{char}"}}]/
    return if password =~ regex
    errors.add :password, 'must contain special character'
  end

  def password_contains_number
    return if password.count("0-9") > 0
    errors.add :password, 'must contain at least one number'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    #memoization
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def index
        render "customers/index"
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :ensure_user_logged_in

    def index
        render "index"
    end
end

app/controllers/menu_categories_controller.rb
class MenuCategoriesController < ApplicationController

    def index
        render "index"
    end

    def create
        new_category = MenuCategory.create!(name: params[:name])
    end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
    def create
        new_category = MenuItem.create!(
            menu_category_id: params[:menu_category_id],
            name: params[:name],
            desc: params[:desc],
            price: params[:price]
        )
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
    def index
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :ensure_user_logged_in

    def new
        render "new"
    end

    def create_customer
        user = User.find_by(email: params[:email])
        if user
            @role = user.role
            if @role == "customer"
                if user.authenticate(params[:password])
                    session[:current_user_id] = user.id
                    redirect_to "/customers"
                else
                    flash[:error] = "Login Invalid! Please retry."
                    redirect_to "/"
                end
            else
                flash[:error] = "Please login through owner portal!"
                redirect_to "/"
            end
        else
            flash[:error] = "No such account found!"
            redirect_to "/"
        end
    end

    def create_owner
        user = User.find_by(email: params[:email])
        if user
            @role = user.role
            if @role == "owner"
                if user.authenticate(params[:password])
                    session[:current_user_id] = user.id
                    redirect_to menu_categories_path
                else
                    flash[:error] = "Login Invalid! Please retry."
                    redirect_to "/signin"
                end
            else
                flash[:error] = "Please login through customer portal!"
                redirect_to "/"
            end
        else
            flash[:error] = "No such account found!"
            redirect_to "/signin"
        end
    end


    def destroy
        session[:current_user_id] = nil
        @current_user = nil
        redirect_to "/"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :ensure_user_logged_in

    def new
        render "users/new"
    end

    def create
        new_user = User.create(
            name: params[:name],
            email: params[:email],
            password: params[:password],
            role: "customer"
        )
        if new_user.save
            session[:current_user_id] = new_user.id
            redirect_to "/"
        else
            flash[:error] = new_user.errors.full_messages.join(", ")
            redirect_to new_user_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_categories_helper.rb
module MenuCategoriesHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<head>
    <title> Cafeteria app </title>
</head>

<body>
    <main class = "Home-main">
        <h1 class = "Home-title">Cafeteria App</h1>

        <section class = "UsersNew">
            <%= form_with(url: customer_sessions_path, method: "post") do |form| %>
                <div class = "Form-section">
                    <p class = "FormInput-label">Email: </p>
                    <%= form.email_field :email, class: "Form-input" %>
                </div>

                <div class = "Form-section">
                    <p class = "FormInput-label">Password: </p>
                    <%= form.password_field :password, class: "Form-input" %>
                </div>

                <div class = "Form-section">
                    <%= form.submit "Sign-in", class: "Form-section-submit" %>
                </div>

                <div class = "Form-section-links">
                    <%= link_to "New user? Sign-up!", new_user_path %>
                    <%= link_to "Owner portal", owner_sessions_page_path %>
                </div>
            <% end %>
        </section>
    </main>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeteriaAppSaas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
        Welcome <%= @current_user.name %>
        <%= link_to "Sign-out", destroy_session_path, method: "delete" %>
      </p>
    <% end %>

    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/menu_categories/index.html.erb
<head>
    <title>Owners portal</title>
</head>
<body>
    <main class="MenuPage-main">
        <h1>Menu</h1>
        <% MenuCategory.all.each do |category| %> <br><br>
            * <%= category.name %><br>
            <% category.menu_items.each do |item| %>
                <%= item.name %> |
                <%= item.desc %> |
                <%= item.price %>
            <% end %> 
        <% end %>
    </main>
</body>

app/views/users/new.html.erb
<article class="UsersNew-main">
<p class="NewUsers-title">Welcome new user! Sign-up!</p>

<section class = "UsersNew">
    <%= form_with(url: users_path, method: "post") do |form| %>
        <div class = "Signup-Form-section">
            <p class="Signup-FormInput-label">Name: </p>
            <%= form.text_field :name, class: "Form-input" %>
        </div>
        
        <div class = "Signup-Form-section">
            <p class="Signup-FormInput-label">Email: </p>
            <%= form.email_field :email, class: "Form-input" %>
        </div>

        <div class = "Signup-Form-section">
            <p class="Signup-FormInput-label">Password: </p>
            <%= form.password_field :password, class: "Form-input" %>
        </div>
        <p class="Password-format">(Use at least 8 characters, 1 digit, 1 lower_case character, 1 upper_case character, 1 symbol)</p>

        <div class = "Signup-Form-section-submit">
            <%= form.submit "Sign Up!", class: "Signup-Form-submit" %><br>
            <%= link_to "Home", "/" ,class: "Signup-Form-HomeLink"%>
        </div>
    <% end %>
</section>
</article>